---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    gitops.k8s-platform/generated-at: '2026-10-03T08:43:07.085593'
    gitops.k8s-platform/source: llm-generated
  labels:
    app: '123'
  name: '123'
  namespace: user-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: '123'
  template:
    metadata:
      labels:
        app: '123'
    spec:
      containers:
      - env: []
        image: nginx:latest
        name: '123'
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
