---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: '123'
  name: '123'
  namespace: user-demo
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: '123'
  type: ClusterIP
