---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: zt-smoke
  name: zt-smoke
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: zt-smoke
  type: ClusterIP
