---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    gitops.k8s-platform/generated-at: '2026-05-19T19:06:49.845238'
    gitops.k8s-platform/source: llm-generated
  labels:
    app: '123456987'
  name: '123456987'
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: '123456987'
  template:
    metadata:
      labels:
        app: '123456987'
    spec:
      containers:
      - env: []
        image: nginx:latest
        name: '123456987'
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
