---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dashtestapp
  name: dashtestapp
  namespace: user-dashtest1789887640
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: dashtestapp
  type: ClusterIP
